# Generated by Django 4.2.7 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro utilisé pour le SMS de confirmation', max_length=20),
        ),
    ]
