# Generated by Django 4.2.7 on 2026-04-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_order_validated_at_order_validation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_location', models.CharField(blank=True, help_text='Lieu du scan (ex: Entrée principale)', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='museum.order')),
            ],
        ),
    ]
