# Generated by Django 4.2.7 on 2026-04-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_scanlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanlog',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Historique de scan', 'verbose_name_plural': 'Historiques de scan'},
        ),
    ]
