# Generated by Django 4.2.7 on 2026-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_contact_staffmember_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('conservateur', 'Conservateur / Conservatrice'), ('guide', "Agent d'accueil et de guidage"), ('bibliotheque', 'Chef de service de la bibliothèque'), ('musee', 'Chef de service du musée'), ('conservation', 'Chef de service de la conservation'), ('saf', 'Chef de service des affaires financières'), ('rh', 'Responsable des ressources humaines'), ('informatique', 'Chef de division informatique'), ('communication', 'Chef de division communication'), ('administration', 'Assistant administratif'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Rôle'),
        ),
    ]
